version: '3.8'
services:
  diffrhythm:
    build: 
      context: .
      dockerfile: Dockerfile
    image: diffrhythm
    container_name: diffrhythm
#    volumes:
#      - ./scripts:/app/scripts
#      - ./output:/app/output
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    stdin_open: true
    tty: true
    command: ["/bin/bash", "-c", "tail -f /dev/null"]
